# routes.yaml
controllers:
    resource:
        path: '../src/Controller/'
        namespace: 'App\Controller\\'
    type: attribute
app_domain_show:
    path: '/domain/{id}'
    controller: 'App\Controller\DomainController::show'
    requirements:
        id: '\d+'