controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

lift_add:
  path: /lifts/add/{id}
  controller: App\Controller\CreateTrailController::addLift
  methods: [GET, POST]
